display:
  background_image: https://tetacourse.com/uploads/posts/2020-07/1595211523_1.jpg
jobs:
  - name: lab-prep
    plan:
      - get: git-resource
        trigger: true
      - task: lab_prep
        file: git-resource/tasks/aws_deploy/basic_workflow.yml

  - name: california
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: aws_deploy_key
        file: git-resource/tasks/aws_deploy/california/aws_key_deploy.yml
      - task: aws_deploy_vpc
        file: git-resource/tasks/aws_deploy/california/aws_env_deploy.yml
      - task: aws_deploy_ubuntu_california
        file: git-resource/tasks/aws_deploy/california/aws_deploy_centosyml

  - name: super-car-trader
    public: true
    plan:
      - get: git-resource
      - task: aws_super_car_trader
        file: git-resource/tasks/setup_supercar_trader_app_v2/input/super-car-trader.yml


  - name: ap-south-1-mumbai
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: aws_deploy_key
        file: git-resource/tasks/aws_deploy/mumbai/aws_key_deploy.yml
      - task: aws_deploy_vpc
        file: git-resource/tasks/aws_deploy/mumbai/aws_env_deploy.yml
      - task: aws_deploy_ubuntu_mumbai
        file: git-resource/tasks/aws_deploy/mumbai/aws_deploy_centosyml

resource_types:
resources:
  - name: git-resource
    source:
      Username: ((Username))
      branch: ((git-branch))
      email: ((email))
      private_key: ((private_key))
      uri: ((git-uri))
    type: git
