display:
  background_image: https://tetacourse.com/uploads/posts/2020-07/1595211523_1.jpg
jobs:
  - name: lab-prep
    plan:
      - get: git-resource
        trigger: true
      - task: lab_prep
        file: git-resource/tasks/aws_deploy/vault_prep.yml

  - name: deploy-aws-key
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: aws_deploy_key
        file: git-resource/tasks/aws_deploy/aws_key_deploy.yml

  - name: deploy-aws-vpc
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: deploy-aws-vpc
        file: git-resource/tasks/aws_deploy/aws_env_deploy.yml

  - name: delete-aws-vpc
    public: true
    plan:
      - get: git-resource
        passed: [deploy-aws-vpc]
      - task: delete-aws-vpc
        file: git-resource/tasks/aws_delete/aws_vpc_delete.yml

  - name: deploy-aws-ubuntu
    public: true
    plan:
      - get: git-resource
        passed: [deploy-aws-vpc]
      - task: deploy-aws-ubuntu
        file: git-resource/tasks/aws_deploy/aws_deploy_ubuntu.yml

  - name: delete-aws-ubuntu
    public: true
    plan:
      - get: git-resource
        passed: [deploy-aws-ubuntu]
      - task: delete-aws-ubuntu
        file: git-resource/tasks/aws_delete/aws_ubuntu_delete.yml


  - name: deploy-te-agent
    public: true
    plan:
      - get: git-resource
        passed: ['deploy-aws-ubuntu']
      - task: deploy-te-agent
        file: git-resource/tasks/te/te_config/input/install_te_agent_task.yml

  - name: deploy-te-agents
    public: true
    plan:
      - get: git-resource
      - task: deploy-te-agents
        file: git-resource/tasks/te/te_config/input/install_te_agents_task.yml

  - name: deploy-appd-agents
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: deploy-appd-agents
        file: git-resource/tasks/te/te_config/input/install_te_agent_task.yml

  - name: deploy-aws-centos
    public: true
    plan:
      - get: git-resource
        passed: [deploy-aws-vpc]
      - task: deploy-aws-centos
        file: git-resource/tasks/aws_deploy/singapore/aws_key_deploy.yml

  - name: delete-aws-centos
    public: true
    plan:
      - get: git-resource
        passed: [deploy-aws-centos]
      - task: delete-aws-centos
        file: git-resource/tasks/aws_deploy/singapore/aws_key_deploy.yml


resource_types:
resources:
  - name: git-resource
    source:
      Username: ((Username))
      branch: ap-south-1a
      email: ((email))
      private_key: ((private_key))
      uri: ((git-uri))
    type: git
