---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: te_agent

params:
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))
  NAME: us-west-1a

run:
  path: /bin/sh
  args:
    - -ce
    - |
      cd te_agent
      python3 -m pip install --upgrade pip
      pip3 install netmiko
      apt -y install ncurses-term
<<<<<<< HEAD
      chmod a+x uninstall_te_agent.sh
      ./uninstall_te_agent.sh
=======
      chmod a+x configure_te_agent.sh
      ./configure_te_agent.sh
>>>>>>> 08cdad69cba2e561cf1308f4beabd8068ae0fe57







