resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/anujmodi1/ciscolivedemo.git


jobs:
  - name: deploy-thousandeyes-agents
    plan:
      - get: repo
      - task: deploy-thousandeyes-agents-task
        params:
          TE_token: xxxx
        config:

          # Tells Concourse which type of worker this task should run on
          platform: linux
          # This is one way of telling Concourse which container image to use for a
          # task. We'll explain this more when talking about resources
          image_resource:
            type: registry-image
            source:
              repository: sconrod/thousandeyes-image
              tag: 1 # images are pulled from docker hub by default
          # The command Concourse will run inside the container
          # echo "Hello world!"
          inputs:
          - name: ci
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                pwd
                ls -la  
                chmod a+x te_api.sh
                ./te_api.sh

