---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: git-resource

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  NAME: ap-south-1a
  REGION: ap-south-1
  AZ: ap-south-1a
  VAULT_ADDR: http://dev-vault.ciscolivedemo2022.com:8200
  SSH_TOKEN: hvs.CAESILe4umJWqNJEnBJYnziN9rS66XzuPIC6C5fy6FiKqiJBGh4KHGh2cy5jSk5DR3FpSW5NMFJmMTlrcXcwc25UbVY

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export NAME
      echo $NAME
      export VAULT_ADDR=$VAULT_ADDR
      export VAULT_TOKEN=$SSH_TOKEN
      vault login --no-print $VAULT_TOKEN
      echo $REGION
      echo $AZ
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      export router_sg_id=$(vault kv get --field=router_sg_id concourse/main/$NAME/router_sg_id)
      chmod a+x git-resource/tasks/aws_deploy/vault_prep.sh
      ./git-resource/tasks/aws_deploy/vault_prep.sh

