---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2

inputs:
  - name: git-resource

params:
  VAULT_ADDR: http://dev-vault.ciscolivedemo2022.com:8200
  SSH_TOKEN: ((ssh-token.token))
  #SSH_TOKEN: hvs.CAESIIqne-UfetUL3M7TTymTpqUagxe_g7NxhO1F2YV6Mxe7Gh4KHGh2cy5QbmlJOGpOcnlWaDlnZ3hrTGRmVFNjNE8
  #SSH_TOKEN: xxxxx

run:
  path: /bin/sh
  args:
    - -ce
    - |
      chmod a+x git-resource/tasks/aws_deploy/vault_prep.sh
      ./git-resource/tasks/aws_deploy/vault_prep.sh


      