---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: anujmodi1/dockerimage
    tag: latest

inputs:
  - name: git-resource

params:
  VAULT_ADDR: http://dev-vault.ciscolivedemo2022.com:8200
 # SSH_TOKEN: ((ssh-token.token))
  NAME: us-east-1
run:
  path: /bin/sh
  args:
    - -ce
    - |
      chmod a+x git-resource/tasks/aws_deploy/vault_prep.sh
      ./git-resource/tasks/aws_deploy/vault_prep.sh


